filebeat.inputs:
- type: container
  paths:
    - '/var/lib/docker/containers/*/*.log'
  
  processors:
  - add_docker_metadata:
      host: "unix:///var/run/docker.sock"
  
  - drop_event:
      when:
        not:
          or:
            - contains:
                docker.container.name: "contextchain-kafka"
            - contains:
                docker.container.name: "contextchain-zookeeper"
            - contains:
                docker.container.name: "contextchain-akhq"
            - contains:
                docker.container.name: "contextchain-kafdrop"
            - contains:
                docker.container.name: "contextchain-schema-registry"
            - contains:
                docker.container.name: "contextchain-kafka-connect"
  
  fields:
    log_type: container
    environment: contextchain
  fields_under_root: false

output.kafka:
  hosts: ["contextchain-kafka:9092"]
  topic: "kafka-logs"
  partition.round_robin:
    reachable_only: false
  
  required_acks: 1
  compression: lz4
  max_message_bytes: 1000000

logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644

processors:
- add_host_metadata: ~
- add_docker_metadata: ~
- decode_json_fields:
    fields: ["message"]
    target: ""
    overwrite_keys: true
