# Filebeat Configuration for ContextChain
filebeat.inputs:
- type: container
  paths:
    - '/var/lib/docker/containers/*/*.log'
  fields:
    logtype: docker
    environment: contextchain
    project: cortext_redis
  fields_under_root: true
  processors:
  - add_docker_metadata:
      host: "unix:///var/run/docker.sock"

# Redis specific log collection
- type: log
  paths:
    - '/var/lib/docker/volumes/contextchain_redis_master_data/_data/*.log'
    - '/var/lib/docker/volumes/contextchain_redis_slave_data/_data/*.log'
  fields:
    logtype: redis
    environment: contextchain
    project: cortext_redis
  fields_under_root: true

output.logstash:
  hosts: ["contextchain-logstash:5044"]

processors:
- add_host_metadata:
    when.not.contains.tags: forwarded
- add_cloud_metadata: ~
- add_docker_metadata: ~

logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644

# Setup template
setup.template.name: "contextchain"
setup.template.pattern: "contextchain-*"
setup.template.enabled: true
